# -*- coding: utf-8 -*-
"""UNgudided

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jm4Bi0kTqT6XrOVxMyf7eBoLhc_N0DKS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("/content/food_orders_new_delhi (1).csv")

data.head()

data.tail()

data.shape

data.isna().sum()

data.info()

data.describe()

mean_Delivery_fee= data["Delivery Fee"].mean()
min_Delivery_fee=data["Delivery Fee"].min()
max_Delivery_fee=data["Delivery Fee"].max()
print(mean_Delivery_fee)
print(min_Delivery_fee)
print(max_Delivery_fee)

plt.boxplot(data["Delivery Fee"])

plt.figure(figsize=(6,2))
plt.boxplot(data['Refunds/Chargebacks'],vert=False,showmeans=True)
plt.grid()
plt.title("This is a Boxplot for the Refunds/Chargebacks:")
plt.xlabel("Refunds/Chargebacks")
plt.show()

plt.hist(data['Refunds/Chargebacks'],bins=10)
plt.grid(axis='y')
plt.title("This is a Histogram for the Age of patients:")
plt.xlabel("Refunds/Chargebacks")
plt.ylabel("frequency:")
plt.show()

plt.pie(data["Order ID"])
plt.show()

import matplotlib.pyplot as plt
# Create a scatter plot of BMI vs Glucose
plt.scatter(data["Delivery Fee"], data["Refunds/Chargebacks"])
plt.xlabel("Delivery Fee")
plt.ylabel("Refunds/Chargebacks")
plt.title("Scatter Plot of Delivery Fee vs Refunds/Chargebacks")
plt.show()

